### ISSUE TITLE
[ToDo] Chat backend API v1

### ISSUE THREAD

**Issue by William-An** [PikaCourse/homiehomie#157]
# TODO: Chat backend API v1

## What is this todo related to?

backend

## What is the todo?

Chat backend API todos:

### TODO

1. [x] Realtime sending and receiving
1. [x] Support chatting also save chat
2. [x] Support partially loading chat history
3. [ ] Private chat?

## How urgent is the todo?

as soon as possible
