### ISSUE TITLE
Alpha v1 frontend todo

### ISSUE THREAD

**Issue by MARX1108** [PikaCourse/homiehomie#3]
# frontend todo
- [x] **transit to ant design**  #21 
## Scheduler component  @joannafg 
- [x] **remove course** (behavior)
- [x] remove milestone/task/allday/specific date on calendar view (style)
- [x] stylize calendar: border/grid (style)
- [x] event onclick popup style (style)
## WiKiNotebook component @kimonazj 
- [x] **load questions/notes** (behavior)
- [x] **save/submit notes** (behavior)
- [x] like/dislike button (behavior)
- [x] textarea and save button when edit (style)
## Wiki Summary component
- [x] wikisummary toggle to add to calendar #2 (behavior) @joannafg 
     - [x] preview course on calendar
     - [x] preview bugs #15 @MARX1108 
     - [x] remove button @joannafg  #11 
- [x] prevent same course to be added @joannafg 
     - [x] color bug #14 
- [ ] download/print calendar
## Header Component
- [x] Approximate course matching (behavior)
- [x] logo and search bar position
