### ISSUE TITLE
[ToDo] LOGO & Product Name

### ISSUE THREAD

**Issue by MARX1108** [PikaCourse/homiehomie#32]
**What is this todo related to?**
check one or more of the following and **add the according labels to the issue**
- [ ] frontend
- [ ] backend
- [x] UI/UX
- [x] administration
- [ ] others (i.e. documentation/bug)

**What is the todo?**
We need a better website name, logo and possibly new visual language
**How urgent is the todo?**

check one or more of the following
Should this be done... 
- [x] as soon as possible
- [ ] anytime within the current development cycle
- [ ] anytime within the next development cycle
- [ ] sometime
note: if it is critically urgent, please add "!important" label

**Additional context**
