### ISSUE TITLE
Alpha v1 backend todo

### ISSUE THREAD

**Issue by William-An** [PikaCourse/homiehomie#4]
First version of homiehomie backend, providing basic data model instance modification

1. [x] Scheduler
    1. [x] Model
    2. [x] API Documentation
    3. [x] API Backend implementation
    3. [x] Add course section num field?
    4. [x] Set up test
        1. [x] Test model method
        2. [x] Test view
            1. [x] Testcases against empty db
            2. [x] Testcases against db with data
        3. [x] Coverage report
        4. [x] GitHub action
            1. [x] Django CI + Deploy to test server
    5. [x] API Post and Put
        1. [x] Create/Modify question
        2. [x] Create/Modify note
        3. [x] Create/Modify Post
        4. [x] Create/Modify PostAnswer
    6. [x] API Delete
        1. [x] API Doc
        2. [x] API Implementation
            1. [x] Post answer deletion
9. [ ] Importing Course
    1. [x] Detail schema of course data
    2. [ ] VT: [portal](https://apps.es.vt.edu/ssb/HZSKVTSC.P_ProcRequest)
    2. [ ] Purdue via API: [portal](https://purdue.io/)
    3. [ ] UNC via pdf miner: [portal](https://registrar.unc.edu/courses/schedule-of-classes/)
    4. [x] BU via scraper: [search portal](https://www.bu.edu/phpbin/course-search/search.php?page=w0&pagesize=-1&adv=1&nolog=&search_adv_all=&yearsem_adv=2021-SPRG&credits=*&hub_match=all&pagesize=-1)
    4. [x] Maryland via scraper: [portal](https://app.testudo.umd.edu/soc/202101/AASP)
