### ISSUE TITLE
User system backend api development v1.0.0b

### ISSUE THREAD

**Issue by William-An** [PikaCourse/homiehomie#55]
1. [ ] ~~login/register recaptcha? #5~~
2. [x] User login api
3. [x] User register api
    1. [x] Verify student email to be school email #7 
    2. [ ] ~~Send user email to move user status from `waiting_email` to `verified` #6 ?~~
4. [x] User profile API
    1. [x] Get user profile
    2. [x] Update user profile
5. [x] Permission system and group
    1. [x] Course and CourseMeta do not requires permission
    2. [x] Note, question, and Post
        1. [x] Get do not need authentication
        2. [x] Post new item need isAuthenticated
        3. [x] Update need IsOwner and Authenticated
