### ISSUE TITLE
[ToDo] Debug and setting config before launch

### ISSUE THREAD

**Issue by William-An** [PikaCourse/homiehomie#68]
**What is this todo related to?**

frontend
backend

**What is the todo?**

Remove debug information from site to prevent expose critical information to public.

1. [x] Frontend
2. [x] Backend
    1. [x] Django in debug
    2. [x] DRF [remove broswable API](https://stackoverflow.com/questions/11898065/how-to-disable-admin-style-browsable-interface-of-django-rest-framework)
    3. [x] Remove any sensitive information like secret key or db connection info
    4. [x] Replace the secret key via setting it in production directly and not store in files

**How urgent is the todo?**

Before `v1.0.0b`

**Additional context**
