### ISSUE TITLE
[ToDo] UserModule Bug & Todo

### ISSUE THREAD

**Issue by joannafg** [PikaCourse/homiehomie#69]
- [ ] (login failed)Error message shown before button loading action is complete 
- [ ] signup page password rules dont change lines / or form a list. 
- [ ] all the "\n" not working 
- [ ] after clicked logout button, it jump to login modal before disappear 
- [ ] loading effect is not used 
- [ ] if user reset password cannot be achieved, use google form
