### ISSUE TITLE
[ToDo] Question and Note Model Moodification

### ISSUE THREAD

**Issue by William-An** [PikaCourse/homiehomie#75]
**What is this todo related to?**

frontend
backend

**What is the todo?**

1. [x] Add private and public note and question
2. [x] Add default three pinned questions for all courses
    1. [x] Consider using the `create_on_query` technique: only create the default questions when the student access the question info related to the course

**How urgent is the todo?**

Before `v1.0.0b`

**Additional context**
