### ISSUE TITLE
[ToDo] Schedule saving and retrieving for user

### ISSUE THREAD

**Issue by William-An** [PikaCourse/homiehomie#76]
**What is this todo related to?**

backend

**What is the todo?**

1. [x] Retrieve the list of user saved schedule
2. [x] Create a new schedule for the user based on the frontend calendar
3. [x] Update a schedule for a user
4. [x] Delete a schedule for a user

**How urgent is the todo?**

Before `v1.0.0b`

**Additional context**
